language: node_js
node_js: 
  - '12'
install:
    - cd $TRAVIS_BUILD_DIR/frontend
    - npm install
    - cd $TRAVIS_BUILD_DIR
before_script:
    - cd $TRAVIS_BUILD_DIR/frontend
script:
    - npm test